name: Publish Firmware

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@cc3e76de337dc59bc1cba8da58d963cd23b873f1 # 2026.9.0
    with:
      files: |
        outequip-ac.yaml
      release-summary: ${{ github.event.release.body }}
      release-url: ${{ github.event.release.html_url }}
      release-version: ${{ github.event.release.tag_name }}

  upload-to-release:
    name: Upload to Release
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@cc3e76de337dc59bc1cba8da58d963cd23b873f1 # 2026.9.0
    needs:
      - build-firmware
    with:
      version: ${{ github.event.release.tag_name }}
